name: Build and deploy .NET Core application to Function App func-rampcast-prod
on:
  push:
    branches:
    - main
permissions:
  id-token: write
  contents: read
env:
  AZURE_FUNCTIONAPP_NAME: func-rampcast-prod
  AZURE_FUNCTIONAPP_PACKAGE_PATH: src/RampCast.Functions/published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 10.0.x
  WORKING_DIRECTORY: src/RampCast.Functions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Setup .NET Core (for inproc extensions)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION_INPROC }}
        dotnet-quality: preview
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: functionapp
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        include-hidden-files: true
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: functionapp
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.func_rampcast_prod_CLIENT_ID }}
        tenant-id: ${{ secrets.func_rampcast_prod_TENANT_ID }}
        subscription-id: ${{ secrets.func_rampcast_prod_SUBSCRIPTION_ID }}
    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
